# Site Settings
title: HIV Worldwide 1990-2015 Visualization
email: aryerpude@dons.usfca.edu
description: >
  A guide to getting started with Jekyll.
baseurl: "/Final-Project"
url: "http://ameyay98.github.io"
github_username:  ameyay98
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM